blank_issues_enabled: false
contact_links:
  - name: Contribution guide
    url: https://github.com/raghavamohan/AnalyticMadhyasthDarshan/blob/master/CONTRIBUTING.md
    about: Full proposal and pull request workflow for studies
