#!/usr/bin/env python3
"""Build, deploy, route, or roll back the generated-PDF R2 Worker."""
from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import _cloudflare_performance as cf
from _common import BASE, configure_utf8_stdio
from _generated_pdf_inventory import generated_pdf_specs, inventory_errors
from _r2_s3 import R2S3Client, load_r2_config

WORKER_NAME = "amd-generated-pdfs"
CANARY_WORKER_NAME = "amd-generated-pdfs-canary"
COMPATIBILITY_DATE = "2026-09-03"
WORKER_ROOT = BASE / "infra" / "generated-pdf-worker"
WORKER_SOURCE = WORKER_ROOT / "src" / "index.js"
KEYS_SOURCE = WORKER_ROOT / "src" / "generated-pdf-keys.js"
ROUTES = (
    f"{cf.SITE_HOST}/Studies/*",
    f"{cf.SITE_HOST}/Applications/*",
)
CANARY_KEYS = (
    "Studies/Nature-Of-Time/Nature-Of-Time.pdf",
    "Studies/A-State-Dynamic-Model-Of-Coexistence/Technical-Note-MD-TOPOS-And-The-State-Dynamic-Model.pdf",
    "Studies/A-State-Dynamic-Model-Of-Coexistence/A-State-Dynamic-Model-Of-Coexistence-Madhyasth-Darshan.pdf",
    "Studies/A-State-Dynamic-Model-Of-Coexistence/A-State-Dynamic-Model-Of-Coexistence-Madhyasth-Darshan-notes.pdf",
)
CANARY_ROUTES = tuple(f"{cf.SITE_HOST}/{key}" for key in CANARY_KEYS)
MANAGED_ROUTES = ROUTES + CANARY_ROUTES


def rendered_keys_module() -> str:
    keys = [spec.key for spec in generated_pdf_specs()]
    encoded = json.dumps(keys, ensure_ascii=False, indent=2)
    return (
        "// Generated by Scripts/_publish_generated_pdf_worker.py --sync-keys. "
        "Do not hand-edit.\n"
        f"export const GENERATED_PDF_KEYS = {encoded};\n"
    )


def sync_keys() -> None:
    KEYS_SOURCE.parent.mkdir(parents=True, exist_ok=True)
    KEYS_SOURCE.write_text(rendered_keys_module(), encoding="utf-8", newline="\n")
    print(f"Wrote {KEYS_SOURCE.relative_to(BASE)}")


def check_sources() -> list[str]:
    errors = inventory_errors()
    if not WORKER_SOURCE.is_file():
        errors.append(f"missing Worker source: {WORKER_SOURCE.relative_to(BASE)}")
    if not KEYS_SOURCE.is_file():
        errors.append(f"missing generated allowlist: {KEYS_SOURCE.relative_to(BASE)}")
    elif KEYS_SOURCE.read_text(encoding="utf-8") != rendered_keys_module():
        errors.append(
            "generated PDF Worker allowlist is stale; run "
            "python Scripts/_publish_generated_pdf_worker.py --sync-keys"
        )
    return errors


def _multipart_put(
    url: str,
    token: str,
    modules: dict[str, str],
    metadata: dict,
) -> dict:
    boundary = uuid.uuid4().hex
    parts: list[bytes] = []

    def add_part(name: str, filename: str, content_type: str, body: bytes) -> None:
        parts.append(
            (
                f"--{boundary}\r\n"
                f'Content-Disposition: form-data; name="{name}"; filename="{filename}"\r\n'
                f"Content-Type: {content_type}\r\n\r\n"
            ).encode("utf-8")
            + body
            + b"\r\n"
        )

    add_part(
        "metadata", "metadata.json", "application/json",
        json.dumps(metadata, separators=(",", ":")).encode("utf-8"),
    )
    for filename, content in modules.items():
        add_part(filename, filename, "application/javascript+module", content.encode("utf-8"))
    parts.append(f"--{boundary}--\r\n".encode("ascii"))
    request = Request(
        url,
        data=b"".join(parts),
        method="PUT",
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": f"multipart/form-data; boundary={boundary}",
        },
    )
    try:
        with urlopen(request, timeout=60) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Worker upload failed: HTTP {exc.code}: {detail}") from exc


def _zone_account_id(token: str, zone_id: str) -> str:
    payload = cf._api_request("GET", f"/zones/{zone_id}", token)
    account_id = ((payload or {}).get("result") or {}).get("account", {}).get("id")
    if not account_id:
        raise RuntimeError("Cloudflare zone response did not include its account ID")
    return str(account_id)


def _workers_subdomain(token: str, account_id: str) -> str:
    payload = cf._api_request("GET", f"/accounts/{account_id}/workers/subdomain", token)
    subdomain = ((payload or {}).get("result") or {}).get("subdomain")
    if not subdomain:
        raise RuntimeError("Cloudflare account has no workers.dev subdomain")
    return str(subdomain)


def deploy_worker(token: str, account_id: str, bucket: str, worker_name: str) -> str:
    metadata = {
        "main_module": "index.js",
        "compatibility_date": COMPATIBILITY_DATE,
        "bindings": [
            {"type": "r2_bucket", "name": "GENERATED_PDFS", "bucket_name": bucket}
        ],
    }
    print(f"Uploading Worker {worker_name!r} with one R2 binding...")
    result = _multipart_put(
        f"{cf.API_BASE}/accounts/{account_id}/workers/scripts/{worker_name}",
        token,
        {
            "index.js": WORKER_SOURCE.read_text(encoding="utf-8"),
            "generated-pdf-keys.js": KEYS_SOURCE.read_text(encoding="utf-8"),
        },
        metadata,
    )
    if not result.get("success", False):
        raise RuntimeError(f"Worker upload was not successful: {result.get('errors')}")
    cf._api_request(
        "POST",
        f"/accounts/{account_id}/workers/scripts/{worker_name}/subdomain",
        token,
        {"enabled": True, "previews_enabled": True},
    )
    hostname = f"{worker_name}.{_workers_subdomain(token, account_id)}.workers.dev"
    print(f"Worker host: https://{hostname}")
    return hostname


def _routes(token: str, zone_id: str) -> list[dict]:
    payload = cf._api_request("GET", f"/zones/{zone_id}/workers/routes", token)
    return list((payload or {}).get("result") or [])


def remote_coverage_errors(client: R2S3Client, keys: tuple[str, ...]) -> list[str]:
    errors: list[str] = []
    for key in keys:
        headers = client.head_object(key)
        if headers is None:
            errors.append(f"missing R2 object: {key}")
            continue
        if headers.get("content-type", "").split(";", 1)[0].lower() != "application/pdf":
            errors.append(f"R2 object is not application/pdf: {key}")
        if not headers.get("x-amz-meta-sha256"):
            errors.append(f"R2 object has no publisher checksum metadata: {key}")
    return errors


def apply_routes(token: str, zone_id: str, patterns: tuple[str, ...]) -> None:
    existing = _routes(token, zone_id)
    for pattern in patterns:
        route = next((item for item in existing if item.get("pattern") == pattern), None)
        if route and route.get("script") == WORKER_NAME:
            print(f"Worker route already configured: {pattern}")
            continue
        body = {"pattern": pattern, "script": WORKER_NAME}
        if route:
            cf._api_request(
                "PUT", f"/zones/{zone_id}/workers/routes/{route['id']}", token, body
            )
            print(f"Updated Worker route: {pattern}")
        else:
            cf._api_request("POST", f"/zones/{zone_id}/workers/routes", token, body)
            print(f"Created Worker route: {pattern}")


def rollback_routes(token: str, zone_id: str) -> None:
    existing = _routes(token, zone_id)
    removed = 0
    for route in existing:
        if route.get("pattern") not in MANAGED_ROUTES or route.get("script") != WORKER_NAME:
            continue
        cf._api_request("DELETE", f"/zones/{zone_id}/workers/routes/{route['id']}", token)
        print(f"Removed Worker route: {route['pattern']}")
        removed += 1
    if not removed:
        print("No managed generated-PDF routes were attached.")


def print_route_status(token: str, zone_id: str) -> None:
    by_pattern = {item.get("pattern"): item.get("script") for item in _routes(token, zone_id)}
    for pattern in MANAGED_ROUTES:
        print(f"{pattern}: {by_pattern.get(pattern) or 'not attached'}")


def purge_keys(token: str, zone_id: str, keys: tuple[str, ...]) -> None:
    urls = [f"https://{cf.SITE_HOST}/{key}" for key in keys]
    cf.purge_cache_files(token, zone_id, urls)


def main(argv: list[str] | None = None) -> int:
    configure_utf8_stdio()
    parser = argparse.ArgumentParser(description=__doc__)
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument("--sync-keys", action="store_true")
    actions.add_argument("--check", action="store_true")
    actions.add_argument("--deploy-canary", action="store_true")
    actions.add_argument("--deploy-production", action="store_true")
    actions.add_argument("--check-r2-coverage", action="store_true")
    actions.add_argument("--apply-canary-routes", action="store_true")
    actions.add_argument("--apply-routes", action="store_true")
    actions.add_argument("--rollback-routes", action="store_true")
    actions.add_argument("--route-status", action="store_true")
    args = parser.parse_args(argv)

    if args.sync_keys:
        sync_keys()
        return 0
    errors = check_sources()
    if errors:
        print("Generated PDF Worker check failed:\n  - " + "\n  - ".join(errors))
        return 1
    if args.check:
        print(f"Generated PDF Worker sources are synchronized ({len(generated_pdf_specs())} keys).")
        return 0

    cf.load_repo_env()
    token = cf.cloudflare_api_token()
    if not token:
        print("CLOUDFLARE_API_TOKEN is required.", file=sys.stderr)
        return 1
    try:
        zone_id = cf.resolve_zone_id(token, cf.cloudflare_zone_id())
        account_id = _zone_account_id(token, zone_id)
        if args.deploy_canary:
            client = R2S3Client(load_r2_config())
            bucket = client.bucket()
            deploy_worker(token, account_id, bucket, CANARY_WORKER_NAME)
        elif args.deploy_production:
            client = R2S3Client(load_r2_config())
            bucket = client.bucket()
            deploy_worker(token, account_id, bucket, WORKER_NAME)
        elif args.check_r2_coverage:
            client = R2S3Client(load_r2_config())
            keys = tuple(spec.key for spec in generated_pdf_specs())
            coverage = remote_coverage_errors(client, keys)
            if coverage:
                raise RuntimeError("R2 inventory coverage failed:\n  - " + "\n  - ".join(coverage))
            print(f"R2 inventory coverage verified ({len(keys)} generated PDFs).")
        elif args.apply_canary_routes:
            client = R2S3Client(load_r2_config())
            coverage = remote_coverage_errors(client, CANARY_KEYS)
            if coverage:
                raise RuntimeError("Canary route gate failed:\n  - " + "\n  - ".join(coverage))
            apply_routes(token, zone_id, CANARY_ROUTES)
            purge_keys(token, zone_id, CANARY_KEYS)
            print_route_status(token, zone_id)
        elif args.apply_routes:
            client = R2S3Client(load_r2_config())
            keys = tuple(spec.key for spec in generated_pdf_specs())
            coverage = remote_coverage_errors(client, keys)
            if coverage:
                raise RuntimeError(
                    "Production route gate failed; every inventory object must be published:\n  - "
                    + "\n  - ".join(coverage)
                )
            apply_routes(token, zone_id, ROUTES)
            purge_keys(token, zone_id, keys)
            print_route_status(token, zone_id)
        elif args.rollback_routes:
            rollback_routes(token, zone_id)
            print_route_status(token, zone_id)
        else:
            print_route_status(token, zone_id)
    except (OSError, RuntimeError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
